services:
  - type: web
    name: gostudybot
    env: python
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CALENDLY_API_KEY
        sync: false
      - key: CALENDLY_CLIENT_ID
        sync: false
      - key: CALENDLY_CLIENT_SECRET
        sync: false
      - key: CALENDLY_REDIRECT_URI
        value: https://gostudybot.onrender.com/auth/callback
